### ISSUE TITLE
Cannot  find configure.sh and cannot compile under ubuntu!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [pr0g/sdl-bgfx-imgui-starter#10]

**Comment by zhangfq-chemistry** [comment]
-- Configuring done
CMake Error at CMakeLists.txt:9 (add_executable):
  Target "sdl-bgfx-imgui-starter" links to target "imgui::imgui" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
-- Configuring done
CMake Error at CMakeLists.txt:9 (add_executable):
  Target "sdl-bgfx-imgui-starter" links to target "imgui::imgui" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by pr0g** [comment]
Hey @zhangfq-chemistry,

Ah, this is probably because we have `configure` scripts for multiple different platforms/generators. Try `configure-ninja.sh` and make sure to do this after following the steps in the third-party folder (see the README.md in there).

Hopefully that should get things working for you, if not let me know,

Thanks!


Tom

**Comment by pr0g** [comment]
I checked the `README.md` and you're totally right they were out of date and confusing, I've updated them now to refer to the explicit `configure-<generator>.sh/bat` files. Hopefully that should fix things for you and be much clearer, give me a shout if not 👍
