### ISSUE TITLE
Compiling multiple files?

### ISSUE THREAD

**Issue by rachitkakkar** [pr0g/sdl-bgfx-imgui-starter#14]
Hello, this project has been very helpful and I was able to follow the instructions to get the demo working. I decided to use this project as a starting point for my engine, and ran into problems when I started abstracting into multiple classes. 

See, I created a `Window.h` header file with the following definition: 
```cpp
class Window {
private:
    SDL_Window* window;
    int width, height;

public:
    Window(const char* title, int width, int height);
    ~Window();
};
```

and a `Window.cpp` file with the following implementation: 
```cpp
Window::Window(const char* title, int w, int h) {
    width = w; height = h;
    window = SDL_CreateWindow(title, SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, width, height, SDL_WINDOW_SHOWN);
    
    if (window == NULL) {
    printf("Window could not be created! SDL_Error: %s\n",
            SDL_GetError());
    }
}

Window::~Window() {
    SDL_DestroyWindow(window);
}
```
I then used the window class in my `main.cpp` file and got the following error
```
Undefined symbols for architecture arm64:
  "Window::Window(char const*, int, int)", referenced from:
      _main in main.cpp.o
  "Window::~Window()", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I have little knowledge of cmake, but I think this has to do with the implementation in the window.cpp file not being compiled (and there are several direct mentions of main.cpp instead of a wildcard *.cpp). When I put the implementation in the main.cpp file, everything worked perfectly. I would appreciate if anyone could help me get all files compiling?

Other Information:
Using Mac OS
Build commands:
```
debug:
	cmake --build build/debug-make
	./compile-shaders-macos.sh

release:
	cmake --build build/release-make
	./compile-shaders-macos.sh
```

**Comment by rachitkakkar** [comment]
I am also a beginner so sorry if this is a dumb question

**Comment by pr0g** [comment]
Hey @rachitkakkar, no worries at all 🙂 

Ah yes, this is because the implementation of your `Window` class (in Window.cpp) isn't getting compiled. To get things to work you'll need to explicitly add `Window.cpp` to the `target_sources` command in the `CMakeLists.txt` file. That should make the link error go away.

It's also good practice to explicitly name the source files you'll be building instead of using a glob pattern (some interesting reasons why are available [here](https://stackoverflow.com/a/32412044/1947066) and [here](https://stackoverflow.com/a/1060061/1947066).
