### ISSUE TITLE
Automatically running third party cMakeLists.txt

### ISSUE THREAD

**Issue by jaquilio** [pr0g/sdl-bgfx-imgui-starter#15]
I am starting on a project that needs bgfx and I would like to use cmake for the build. Since I am new to cmake, I am using this "sdl-bgfx-imgui-starter" as an example of how to go about (Thank you for providing it!).

However, the setup here involves an extra manual step for the user: The user has to first "cd" to the "third-party" folder and run "cmake -B build". What changes are needed to make that automatically happen as part of building the main project? An example of doing that would be great. I would also appreciate any pointers and guidance!

Thanks.

**Comment by jaquilio** [comment]
On second thoughts,  since that manual step is something I can live with at least as of now, closing this.

**Comment by pr0g** [comment]
Hey @jaquilio,

Great to hear the repo is coming in handy! Thanks for the message.

In terms of removing the extra step a really simple solution (hack?) is to just make a little .bat/sh script to invoke the third-party command to grab the dependencies and then do the main build. There is no doubt a way to do this with CMake but I'm not sure what it is off the top of my head sorry.

Another alternative is using `FetchContent` which you can use to build `bgfx` as part of your own build, but the downside is if you want to do a clean build you'd have to rebuild all of `bgfx` again (which takes a little while to build, definitely use the Ninja generator if you can (`-G Ninja`), it's the fastest I've tried).

If you're new to CMake and want to learn a bit more about it feel free to check out another repo of mine called [cmake-examples](https://github.com/pr0g/cmake-examples). It has quite a lot of info on getting started with CMake and installing etc...

Let me know if you have any other questions and I'll see if I can help,

All the best!

Tom

**Comment by pr0g** [comment]
Also I do love issues that close themselves! 😅

**Comment by pr0g** [comment]
Hey @jaquilio!

I wanted to follow up again on this issue...

Ever since you mentioned it, the two-step process has been bugging me (you successfully [Nerd Sniped](https://xkcd.com/356/) me 😂). What you were asking should be possible and I've been slowly mulling it over and doing some research into a technique called _superbuilds_ which you can use with CMake and `ExternalProject_Add`.

I think I've finally landed on something that works and allows the whole project (dependencies and application) to be built from one command 🥳 .

You can check out the changes here - https://github.com/pr0g/sdl-bgfx-imgui-starter/compare/main...superbuild (I haven't merged them to `main` yet as there's still a bunch of testing I need to do for all the different configs and platforms to check I haven't inadvertently broken anything but it seems to be on the right track).

Commit https://github.com/pr0g/sdl-bgfx-imgui-starter/commit/3e23cdaec000da34da6c7808f625ed5b47ec0eab is the first version which will build all third-party dependencies and the main application from one command (just use `cmake -B <build-folder> -G <generator> -DCMAKE_BUILD_TYPE=<build-type> -DSUPERBUILD=ON`). The one problem with this version though is the third-party dependencies all end up in that `build` folder and not in the `third-party/build` folder which is a bit of a pain as then it's annoying if you want to delete your application build folder separate from the third-party dependencies.

However commit https://github.com/pr0g/sdl-bgfx-imgui-starter/commit/840e87acb5eba34906d8016da9634f0d3f1a61ce improves on this by specifying the third-party dependencies should be built in the `third-party/build` folder, keeping them separate which is good. The main project just has to know where to look for those folders as before using `-DCMAKE_PREFIX_PATH`.

The last important commit https://github.com/pr0g/sdl-bgfx-imgui-starter/commit/811e8acf68b3a0fbd3c30d80f50fff0022fb44c1, makes sure the builds for different configs go to different folders to stop them overwriting each other.

It's still a WIP but I wanted to let you know, please do give it a try and let me know if you run into any issues! I'll keep iterating on it and testing to see if I can get it merged back to `main` before too long.

Cheers!
