### ISSUE TITLE
Multi-viewport support?

### ISSUE THREAD

**Issue by wobes1** [pr0g/sdl-bgfx-imgui-starter#7]
Hello,

Thank you so much for the starter kit of sdl bgfx and imgui. 
I was able successfully integrate it with c99 project using cimgui. 

I have a question for you. Have you figured out docking branch support of imgui? I got docking working out of the box with impl_bgfx but not able to support multi-viewport since bgfx clips off the rendering of imgui windows which are not in SDL window rect.  

Thank you.

**Comment by pr0g** [comment]
Hey @wobes1

Thanks for the kind words! Really glad it's been useful.

I'm afraid I haven't looked into that at all but if it's a bgfx issue it might be worth bringing it up in the bgfx repo (https://github.com/bkaradzic/bgfx) or the bgfx Discord (https://discord.gg/CdNK9x4Y). Discord might be a good place to start.

If it's something with SDL then it might be something we have to look into but I'm not sure right now.

Cheers!

Tom

**Comment by wobes1** [comment]
Thank you for your reply @pr0g 

I reached out to bgfx community and one person was able to point out that they were able to figure it out with glfw.
https://github.com/HippoPlayer/HippoPlayer/blob/im-experiment/src/hippo_vis/hippo_vis.cpp#L230-L235

I did try to integrate it to impl_sdl but I will also need to update impl_bgfx to the latest version which supports multiple views as far as I understood. 

Anyhow, I will close the issue and shall I come up with a solution, would you like me to submit a pull request? It could be a separate branch for docking or just an extra feature. 

All the best,

Alexander

**Comment by pr0g** [comment]
No problem at all @wobes1,

Oh fantastic, that's great to hear!

So for full context the impl_sdl files are a clone from those files in the imgui repo so if that does need to be updated it would be best to have the changes accepted there and we can then duplicate them here (would be nice if we could depend on them but that's out of scope for this most likely). Essentially we want to avoid diverging from the source of truth in this case.

It is likely okay to modify impl_bgfx so long as it's compatible with vanilla bgfx and imgui (not a WIP branch). If the changes are small and compatible it should be fine to update. We could maybe introduce a CMake variable in the third party folder to select a different version of imgui to pull in if needed to support multi-viewports.

A PR is fine so long as it's not a breaking change and doesn't increase complexity too much. If that's the case a branch might be the way to go (at least short term until the multi-viewport imgui changes are stable).

Does that sound okay/make sense? Making a fork to experiment with these changes is likely the best way to go.

Thanks for your time,


Tom

**Comment by wobes1** [comment]
Hey Tom,

Absolutely. One point though that imgui docking branch is pretty stable and is working on constantly.  (last time updated 10 days ago) and event sometimes it is suggested to go with docking branch rather than master.

The SDL change is pretty small (just extra locs) to support IoPlaftorm callbacks. However, what might need a rework is bgfx implementation. I will have to see if it would be compatible with both imgui branches (most likely yes). But I believe having docking with SDL and BGFX is rather a hot topic even on bgfx discord :)

Cheers!

**Comment by pr0g** [comment]
Hey Alexander,

Okay cool, that's good to know. Perhaps we could use a CMake option to decide what version of Dear ImGui to pull down.

It would be possible to change this line in the `CMakeLists.txt` file...

```
UPDATE_COMMAND bash <SOURCE_DIR>/git-clone.sh imgui
```

to be...

```
UPDATE_COMMAND bash <SOURCE_DIR>/git-clone.sh imgui docking
```

So that branch will be built (it would be nice to have to opt into this though, as that branch might disappear in future if everything does get merged to the main branch, which would cause this repo to break).

If it's possible to have the changes in the `imgui_impl_bgfx.h/cpp` work with either version of the library then that'd be perfect. It's possible `imgui_impl_sdl.h/cpp` have already been updated in the `docking` branch of the Dear ImGui repo so again we could just have a copy of those files that can be optionally included instead of the default ones if a particular option is set.

Let me know what you decide, even if the change stays as a fork people who want docking can just use that instead and I don't intend to make large changes here in future (just updates to the version of the libraries used every once in a while 🙂).
